namespace BlogApp.Shared.Infrastructure.Swagger;

public static class SwaggerExtensions
{
    public static IServiceCollection AddSwaggerDocumentation(this IServiceCollection services)
    {
        services.AddOpenApiDocument(options =>
        {
            options.DocumentName = "v1";
            options.Title = "Blog App API";
            options.Version = "v1";
            options.Description = "Professional Blog Application API";

            // Add JWT Authentication support
            options.AddSecurity("Bearer", [], new OpenApiSecurityScheme
            {
                Type = OpenApiSecuritySchemeType.Http,
                Scheme = "Bearer",
                BearerFormat = "JWT",
                Description = "Enter your valid token in the text input below.\r\n\r\nExample: \"eyJhbGciOiJIUzI1Ni...\""
            });

            options.OperationProcessors.Add(new AspNetCoreOperationSecurityScopeProcessor("Bearer"));
        });

        return services;
    }

    public static IApplicationBuilder UseSwaggerDocumentation(this IApplicationBuilder app)
    {
        app.UseOpenApi(); // Serves the OpenAPI/Swagger JSON document

        // Configures the Swagger UI
        app.UseSwaggerUi(settings =>
        {
            settings.Path = "/swagger"; // Default path
            // NSwag automatically finds the document generated by UseOpenApi()
        });

        return app;
    }
}