<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>331ff8a9-a4bb-41d0-91b1-afb4b1d9a28d</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="wwwroot\**" />
	  <Content Remove="wwwroot\**" />
	  <EmbeddedResource Remove="wwwroot\**" />
	  <None Remove="wwwroot\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="NetEscapades.AspNetCore.SecurityHeaders" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Aspire\BlogApp.ServiceDefaults\BlogApp.ServiceDefaults.csproj" />
		<ProjectReference Include="..\..\Modules\Blog\BlogApp.Modules.Blog.Infrastructure\BlogApp.Modules.Blog.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Modules\Blog\BlogApp.Modules.Blog.Presentation\BlogApp.Modules.Blog.Presentation.csproj" />
		<ProjectReference Include="..\..\Modules\Identity\BlogApp.Modules.Identity.Infrastructure\BlogApp.Modules.Identity.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Modules\Identity\BlogApp.Modules.Identity.Presentation\BlogApp.Modules.Identity.Presentation.csproj" />
		<ProjectReference Include="..\..\Shared\BlogApp.Shared.Presentation\BlogApp.Shared.Presentation.csproj" />
	</ItemGroup>

</Project>
