<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\BlogApp.Shared.Presentation\BlogApp.Shared.Presentation.csproj" />
    <ProjectReference Include="..\BlogApp.Modules.Blog.Application\BlogApp.Modules.Blog.Application.csproj" />
    <ProjectReference Include="..\BlogApp.Modules.Blog.Infrastructure\BlogApp.Modules.Blog.Infrastructure.csproj" />
  </ItemGroup>

</Project>
