<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>0dc1a2e6-b75a-4e55-9817-70a68a25495a</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
		<PackageReference Include="Aspire.Hosting.Redis" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Bootstrapper\BlogApp.Web\BlogApp.Web.csproj" />
	</ItemGroup>

</Project>
